name: Go

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: "false"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.15"

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          mkdir -pv "$(go env GOPATH)/src/github.com/plexdrive"
          ln -nfsv "$PWD" "$(go env GOPATH)/src/github.com/plexdrive/plexdrive"
          go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Upload
        uses: actions/upload-artifact@main
        if: (!cancelled())
        with:
          name: plexdrive
          path: ./plexdrive
